package tv.purple.monolith.component.api.di.scope

const val BTTV = "bttv"
const val CHATTERINO = "chatterino"
const val NOP = "nop"
const val FFZAP = "ffzap"
const val FFZ = "ffz"
const val STV = "stv"
const val STV_OLD_API = "stv_old"
const val PRN = "pronouns"
const val GQL = "GQL"
const val HOMIES = "homies"
const val FLXRS = "flxrs"
const val CHATSEN = "chatsen"
const val CHATSEN2 = "chatsen2"

const val L_EU = "l_eu"
const val L_EU2 = "l_eu2"
const val L_AS = "l_as"
const val PP_EU = "pp_eu"
const val PP_EU2 = "pp_eu2"
const val PP_EU3 = "pp_eu3"
const val PP_EU4 = "pp_eu4"
const val PP_EU5 = "pp_eu5"
const val PP_NA = "pp_na"
const val PP_AS = "pp_as"
const val PP_SA = "pp_sa"
